### ISSUE TITLE
Write Cluster connection details

### ISSUE THREAD

**Issue by merlindorin** [crossplane-contrib/provider-jet-mongodbatlas#10]
When using `writeConnectionSecretToRef` on the `Cluster` resource, no data is provided. Having this data (for example cluster dsn) will simplify the integration (without creating a composition and patching...).

For example:

```
apiVersion: mongodbatlas.jet.crossplane.io/v1alpha2
kind: Cluster
metadata:
  name: demo
spec:
  forProvider:
    projectIdRef:
      name: demo
    providerName: TENANT
    backingProviderName: AWS
    providerRegionName: EU-CENTRAL-1
    providerInstanceSizeName: M0
  writeConnectionSecretToRef:
    name: mongodb-access
    namespace: demo
  providerConfigRef:
    name: default
```
