### ISSUE TITLE
Cannot create user

### ISSUE THREAD

**Issue by Piotr1215** [crossplane-contrib/provider-jet-mongodbatlas#6]
### What happened?

Creating a user MR results in the following error

![image](https://user-images.githubusercontent.com/8086638/159668576-df69d15c-8750-41ff-86a4-1844dce38a7e.png)

### How can we reproduce it?

User YAML

```yaml
apiVersion: database.mongodbatlas.jet.crossplane.io/v1alpha1
kind: User
metadata:
  name: example
  annotations:
    crossplane.io/external-name: example-user
spec:
  forProvider:
    authDatabaseName: admin
    username: example-user
    passwordSecretRef:
      name: user-password
      key: password
      namespace: crossplane-system
    projectId: <project-id>
    roles:
      - databaseName: admin
        roleName: readAnyDatabase
    scopes:
      - name: example-cluster
        type: CLUSTER
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 1.6.0
Provider version: 0.2.1

* Cloud provider or hardware configuration:
* Kubernetes version (use `kubectl version`)
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): KIND
* OS (e.g. from /etc/os-release)
   1   │ NAME="Pop!_OS"
   2   │ VERSION="21.10"
   3   │ ID=pop
   4   │ ID_LIKE="ubuntu debian"
   5   │ PRETTY_NAME="Pop!_OS 21.10"
   6   │ VERSION_ID="21.10"
   7   │ HOME_URL="https://pop.system76.com"
   8   │ SUPPORT_URL="https://support.system76.com"
   9   │ BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
  10   │ PRIVACY_POLICY_URL="https://system76.com/privacy"
  11   │ VERSION_CODENAME=impish
  12   │ UBUNTU_CODENAME=impish
  13   │ LOGO=distributor-logo-pop-os
* Kernel (e.g. `uname -a`)
Linux pop-os 5.16.11-76051611-generic #202202230823~1646248261~21.10~2b22243 SMP PREEMPT Wed Mar 2 20: x86_64 x86_64 x86_64 GNU/Linux
